const Data = [
  {
    id: 1,
    img: "//avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    myName: "Leanne Graham",
    email: "Sincere@april.biz",
    phone: "1-770-736-8031 x56442",
    website: "https://hildegard.org",
  },
  {
    id: 2,
    img: " https://avatars.dicebear.com/v2/avataaars/Antonette.svg?options[mood][]=happy",
    myName: "Ervin Howell",
    email: "Shanna@melissa.tv",
    phone: "010-692-6593 x09125",
    website: "https://anastasia.net",
  },
  {
    id: 3,
    img: "https://avatars.dicebear.com/v2/avataaars/Samantha.svg?options[mood][]=happy",
    myName: "Clementine Bauch",
    email: "Nathan@yesenia.net",
    phone: "1-463-123-4447",
    website: "ramiro.info",
  },
  {
    id: 4,
    img: "https://avatars.dicebear.com/v2/avataaars/Karianne.svg?options[mood][]=happy",
    myName: "Patricia Lebsack",
    email: "Julianne.OConner@kory.org",
    phone: "493-170-9623 x156",
    website: "kale.biz",
  },

  {
    id: 5,
    img: "https://avatars.dicebear.com/v2/avataaars/Kamren.svg?options[mood][]=happy",
    myName: "Chelsey Dietrich",
    email: "Lucio_Hettinger@annie.ca",
    phone: "(254)954-1289",
    website: "demarco.info",
  },
  {
    id: 6,
    img: "https://avatars.dicebear.com/v2/avataaars/Leopoldo_Corkery.svg?options[mood][]=happy",
    myName: "Mrs. Dennis Schulist",
    email: "Karley_Dach@jasper.info",
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
  },
  {
    id: 7,
    img: "https://avatars.dicebear.com/v2/avataaars/Elwyn.Skiles.svg?options[mood][]=happy",
    myName: "Kurtis Weissnat",
    email: "Telly.Hoeger@billy.biz",
    phone: "210.067.6132",
    website: "elvis.io",
  },
  {
    id: 8,
    img: "https://avatars.dicebear.com/v2/avataaars/Maxime_Nienow.svg?options[mood][]=happy",
    myName: "Nicholas Runolfsdottir V",
    email: "Sherwood@rosamond.me",
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
  },
  {
    id: 10,
    img: "https://avatars.dicebear.com/v2/avataaars/Delphine.svg?options[mood][]=happy",
    myName: "Clementina DuBuque",
    email: "Ray.Padberg@karina.biz",
    phone: "024-648-3804 x140",
    website: "http://ambrose.net",
  },
  {
    id: 9,
    img: "https://avatars.dicebear.com/v2/avataaars/Maxime_Nienow.svg?options[mood][]=happy",
    myName: "Glenna Reichert",
    email: "Chaim_McDermott@dana.io",
    phone: "(775)976-9794 x41206",
    website: "http://conrad.com",
  },
];

export default Data;
